import os
import time


def load():
    print("-Please Wait-")
    time.sleep(1)
    print("-We Are Loading For You-")
    os.system("cls")
    print("-        |")
    print("Loading Now")
    time.sleep(1)
    os.system("cls")
    print("--       |")
    print("Loading Now")
    time.sleep(1)
    os.system("cls")
    print("---      |")
    print("Loading Now")
    time.sleep(1)
    os.system("cls")
    print("----     |")
    print("Loading Now")
    time.sleep(1)
    os.system("cls")
    print("-----    |")
    print("Loading Now")
    time.sleep(1)
    os.system("cls")
    print("------   |")
    print("Loading Now")
    time.sleep(1)
    os.system("cls")
    print("-------  |")
    print("Loading Now")
    time.sleep(1)
    os.system("cls")
    print("-------- |")
    print("Loading Now")
    time.sleep(1)
    os.system("cls")
    print("---------|")
    print("Loading Completed")
    time.sleep(1)
    os.system("cls")
